### ISSUE TITLE
Cloud-Run Instances Receiving SIGTERM

### ISSUE THREAD

**Issue by SteGaff7** [ahmetb/cloud-run-faq#149]
Hi,

I currently have multiple APIs deployed as cloud-run instances and have the minimum instances set to 1 for each. The ASP Net Core app within the docker container is restarting at random intervals (sometimes stays active for 2 days, other times 30mins) - this results in the first request to the restated app being slow which accumulates on the front-end quickly.

The container is receiving SIGTERM signal and I am wondering what are the potential causes for cloud-run to signal a container to terminate and restart, especially with the minimum instances set to 1.

Thanks Stephen

**Comment by ahmetb** [comment]
The containers (even with minInstances) will eventually be restarted (due to host machine maintenance, perhaps better binpacking at scheduling layer and such).

However, after the shutdown, if you set minInstances=1, the container should be coming up again (maybe on another host machine). So it would not cause cold-starts.

If you think this is too frequent or causing cold-starts, please visit Google Cloud Issue Tracker and submit a feedback.

**Comment by SteGaff7** [comment]
Thank you
