### ISSUE TITLE
Question: how to run sockets on GKE hosted Run

### ISSUE THREAD

**Issue by intellix** [ahmetb/cloud-run-faq#33]
I've transitioned all of our frontend services to Cloud Run and love it. It'd be great to also move the API there as well but is using web sockets heavily.

Bumped into this FAQ repository which states:

> WebSockets are currently not supported on Cloud Run. However, Cloud Run on GKE supports running applications capable of doing WebSockets.

It says that GKE supports running applications capable of doing websockets but doesn't quite clarify how. 

What limitation does managed Run have that a GKE hosted solution does not suffer from?

**Comment by ibrunotome** [comment]
Hi @intellix, just for curiosity, have you tested you frontend services in cloud run with a load testing service? like loader.io ? I'm asking because I tested on the first days of cloud run, 1000 concurrent connections of a Nuxt.js frontend in cloud run x app engine standard. The cloud run could not handle without a 502 error.

**Comment by intellix** [comment]
To be honest I haven't load tested it but it only reaches about 4req/sec currently and seems perfectly fine atm

**Comment by ahmetb** [comment]
Since Cloud Run on GKE is Knative/Istio stack it supports Websockets. https://github.com/mchmarny/knative-ws-example

Cloud Run managed platform runs on Google’s proprietary networking stack that doesn’t support WS yet.

I would recommend you move the error rates discussion elsewhere like Google Cloud issue trackers or Stackoverflow.

**Comment by sneko** [comment]
Hi @ahmetb ,

Just following the example you provided, when the connection is trying to establish I get the error:
```
app.js:28 WebSocket connection to 'ws://demo.XXXXXXX/ws' failed: Error during WebSocket handshake: Unexpected response code: 503
```

Not that before ending onto this issue and the example, I was also having this error on my own websocket server. I'm running it on Cloud Run on GKE, and when trying to `kubectl port-forward ...` onto the pod directly, I'm able to connect to the server. It seems sometimes goes wrong at another layer (Knative/Istio ?).

I didn't override settings from Cloud Run level (to override Kubernetes settings or other), so I'm a bit lost what could cause this.

If you have any idea, do not hesitate 👍 I continue to investigate today 🤞 

Thank you,

**Comment by sneko** [comment]
Just to follow up @ahmetb , did you succeed using the example you provided with a Cloud Run on GKE cluster?

I tried multiple attempts I described here https://github.com/mchmarny/knative-ws-example/issues/2 but none of them are working. Having your thoughts would be great 🙏 

Thank you,

**Comment by ahmetb** [comment]
I’d open a Knative/Serving issue is you are not able to get WS working on Knative.
