### ISSUE TITLE
Why does Cloud Run respond with status code 429?

### ISSUE THREAD

**Issue by vpontis** [ahmetb/cloud-run-faq#54]
I periodically see Cloud Run respond with 429s as it's spinning up new instances to serve requests. My cold start may take a couple seconds, it's not incredibly slow...

Anyone else experience this? How should I fix / diagnose this?

**Comment by ahmetb** [comment]
Are you in a high QPS app or limiting your max instances to a low number by any chance?

**Comment by vpontis** [comment]
QPS == request count? 

I limited my max instances to 15 because there was weird behavior where if I got 2x the # of requests, I would get 50x the number of instances.

But 15 instances should be more than enough to satisfy avg request load. I usually average 1-2 instances running at a time. 

I get 429s when a new request pins up or a new revision is deployed. I reached out to Cloud Run support and they made this sound like a normal thing...

**Comment by coffenbacher** [comment]
I had this issue when I limited my app to 2 instances, bumping it up to 10 eliminated the errors. The app itself should have been *easily* able to handle 100x the amount of traffic I was getting with its 2 instances, but I suspect something was going on with however Cloud Run manages them, where with only 2 instances they'd get stuck somehow. 

Definitely unexpected but at least it resolved.

**Comment by ahmetb** [comment]
If you can reliably repro this with `gcr.io/google-samples/hello-app:1.0` container or something like that, I'm happy to follow up @coffenbacher.

**Comment by zaddok** [comment]
I am testing out Cloud Run with one of my existing _golang_ _appengine_ projects.  The appengine version only ever needs one instance (the stats show it almost never goes above 1, so I am experimenting configuring Cloud Run with "maximum instances = 1" and "vcpu = 1" as well for testing.

Aside from strange latency to the datastore, my main problem is I get 429 on literally the home/signin page. The first uncached load generates about 10 http requests, but they are all cached after that. I will still see 429 errors on subsequent attempts to use the signin page. 

It is almost like the load balancer/router is super eager to start up new instances, perhaps it is not  willing to wait 10ms to start a new request. But my real question is why would the instance not be accepting requests for even 10ms if I have one web browser attempting to view one page in a sequential (not concurrent) series of requests.

This may be inter-related with the fact that my signin page takes 3 seconds to return, because there are appear to be some latency issues (Cloud run won't allow me to run in the same US region as the location of my datastore – Unfortunately there are a couple of round trips that could be probably be optimised out) 

That said, if a signin page is taking 3s to return, why would there be contention? It's not clear to me if the contention is because the VPS host is pausing, or if there is a problem with the go app not being able to cope with serving one or two sequential HTTP requests.

2020-01-15 07:51:42.240 AEDT POST 200 3.33 KB 3.3 s   Safari 13  https://cloudrun.website.com/signin
2020-01-15 07:51:42.950 AEDT GET  200 100.07 KB 17 ms Safari 13  https://cloudrun.website.com/font/fa-solid-900.woff
2020-01-15 07:51:47.137 AEDT POST 200 3.33 KB 2.9 s   Safari 13  https://cloudrun.website.com/signin
2020-01-15 07:51:49.701 AEDT POST 429 14 B 0 ms       Safari 13  https://cloudrun.website.com/signin

I'd test out increasing the instance limit, but the potential for "bill shock" if I switch over is a little bit terrifying. 😀

**Comment by zaddok** [comment]
Investing another day mucking around with Cloud Run. Even if I bump the max instance count up to two, 429 errors still make it back to the client web browser:

2020-01-15 15:15:31.405 GET 200 3.24 KB 126 ms  https://cloudrun.biblicaltext.com/signin
2020-01-15 15:15:35.024 GET 200 8.38 KB   4 ms  https://cloudrun.biblicaltext.com/z/global.css
2020-01-15 15:15:36.380 GET 429 14 B   0 ms  https://cloudrun.biblicaltext.com/z/signin.css
2020-01-15 15:15:36.380 GET 429 14 B   0 ms  https://cloudrun.biblicaltext.com/z/authentication.js
2020-01-15 15:15:36.789 GET 200 20.45 KB   4 ms  https://cloudrun.biblicaltext.com/logo.png
2020-01-15 15:30:42.174 GET200 3.24 KB 133 ms  https://cloudrun.biblicaltext.com/signin

**Comment by ahmetb** [comment]
Let’s move this to Stack Overflow or Google Cloud Public Issue Tracker. This is not the right forum to continue discussion.
