### ISSUE TITLE
How to prevent spam attacks (ddos)

### ISSUE THREAD

**Issue by laguiz** [ahmetb/cloud-run-faq#70]
Hi,

I like the idea of Cloud Run but what if we get a ddos attack? Cost could explode.

Any recommendation for internet exposed service ?

Regards,
Maxence

**Comment by ahmetb** [comment]
see Cloud Armor point here.
https://github.com/ahmetb/cloud-run-faq#can-serve-cloud-run-services-with-cloud-https-load-balancer

**Comment by StarpTech** [comment]
@ahmetb I don't understand how that point helps to answer the question. Cloud run could still offer such a feature without relying on a custom load balancer. Google could also offer discounts when an attack occurs due to the reduced capabilities in the Cloud run fully managed.

**Comment by StarpTech** [comment]
I think that answer is also valid for cloud run because they are served from the Google frontend server too.

https://stackoverflow.com/a/49953862/1893773

**Comment by ahmetb** [comment]
ALL of Google Cloud IPs are protected against SYN floods. 

However, Cloud Armor is a much more advanced WAF/DDOS filter that we already implemented. So instead of reimplementing it for Cloud Run (fully managed), once Google Cloud Load Balancer can be integrated to Cloud Run, you’ll be able to use Cloud Armor.

**Comment by btilford** [comment]
Looks like non GKE Cloud Run can be put behind Cloud Endpoints which you can configure with quotas etc.

**Comment by StarpTech** [comment]
@ahmetb any ETA?
